nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.2.3.cjs

packageExtensions:
  '@graphql-codegen/cli@*':
    dependencies:
      '@types/node': '^18.11.7'
      'ts-node': '^10.9.1'
      'typescript': '^4.8.4'
  'graphql-config@*':
    dependencies:
      '@types/node': '^18.11.7'
      'typescript': '^4.8.4'
